<?php declare(strict_types = 1);

$form = new CWidgetFormView($data);

$form->addField(new CWidgetFieldMultiSelectGroupView($data['fields']['groupids']));
$form->addField(new CWidgetFieldMultiSelectHostView($data['fields']['hostids']));
$form->addField(new CWidgetFieldSelectView($data['fields']['layout_mode']));
$form->addField(new CWidgetFieldSelectView($data['fields']['port_visual_style']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['columns']));
$form->addField(new CWidgetFieldSelectView($data['fields']['show_alias']));
$form->addField(new CWidgetFieldSelectView($data['fields']['show_utilization']));
$form->addField(new CWidgetFieldSelectView($data['fields']['interface_list_default']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['interface_list_rows']));
$form->addField(new CWidgetFieldSelectView($data['fields']['hide_empty_devices']));
$form->addField(new CWidgetFieldSelectView($data['fields']['show_featured_charts']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['featured_chart_limit']));
$form->addField(new CWidgetFieldSelectView($data['fields']['featured_chart_period']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['featured_chart_height']));
$form->addField(new CWidgetFieldSelectView($data['fields']['show_hardware_health']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['temperature_sensor_regex']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['fan_sensor_regex']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['psu_sensor_regex']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['other_sensor_regex']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['temperature_warning']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['temperature_critical']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['model_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['uptime_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['cpu_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['memory_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['include_regex']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['exclude_regex']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['oper_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['admin_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['name_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['alias_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['speed_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['traffic_in_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['traffic_out_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['errors_in_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['errors_out_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['discards_in_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['discards_out_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['duplex_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['type_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['trunk_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['vlan_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['poe_status_pattern']));
$form->addField(new CWidgetFieldTextBoxView($data['fields']['poe_power_pattern']));

$form->show();
